@Sacurt.VertArch.Api_HostAddress = https://localhost:7294
@Sacurt.VertArch.Api_Key = 626900E4-CA61-41CA-8FCD-FC82F475B88B

GET {{Sacurt.VertArch.Api_HostAddress}}/api/articles?page=1&pageSize=3
Accept: application/json

###

POST {{Sacurt.VertArch.Api_HostAddress}}/api/articles
Accept: application/json
Content-Type: application/json
X-Api-Key: {{Sacurt.VertArch.Api_Key}}

{ 
    "tags": [".net","vert-arch", "c#", "architecture"] 
}

###

GET {{Sacurt.VertArch.Api_HostAddress}}/api/articles/E431C36F-2E6C-4CBB-B6B7-9D08269C7189
Accept: application/json

###

GET {{Sacurt.VertArch.Api_HostAddress}}/api/articles/NOT-EXISTING-ID
Accept: application/json
###

PUT {{Sacurt.VertArch.Api_HostAddress}}/api/articles/E431C36F-2E6C-4CBB-B6B7-9D08269C7189/publish
Accept: application/json

X-Api-Key: {{Sacurt.VertArch.Api_Key}}