@Sacurt.VertArch.Api_HostAddress = https://localhost:7294

GET {{Sacurt.VertArch.Api_HostAddress}}/api/articles
Accept: application/json

###

POST {{Sacurt.VertArch.Api_HostAddress}}/api/articles
Accept: application/json
Content-Type: application/json

{
    "title": "Vertical Architecture",
    "content": "Adopts a feature-based approach, keeping related logic within the same file",
    "tags": [".net","vert-arch", "c#", "architecture"] 
}

###

GET {{Sacurt.VertArch.Api_HostAddress}}/api/articles/370B4604-35A6-4335-AD74-5E6BE9506411
Accept: application/json

###
