@Sacurt.VertArch.Api_HostAddress = https://localhost:7294

GET {{Sacurt.VertArch.Api_HostAddress}}/api/articles?sortColumn=title&sortOrder=desc&page=2&pageSize=3
Accept: application/json

###

POST {{Sacurt.VertArch.Api_HostAddress}}/api/articles
Accept: application/json
Content-Type: application/json

{
    "title": "Vertical Architecture", 
    "tags": [".net","vert-arch", "c#", "architecture"] 
}

###

GET {{Sacurt.VertArch.Api_HostAddress}}/api/articles/370B4604-35A6-4335-AD74-5E6BE9506411
Accept: application/json

###
